// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcDB.Web.Data;

#nullable disable

namespace MvcDB.Web.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("MvcDB.Web.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<int>("JerseyNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PlayerId");

                    b.HasIndex("TeamName");

                    b.ToTable("Player", (string)null);

                    b.HasData(
                        new
                        {
                            PlayerId = 1,
                            FirstName = "Sven",
                            JerseyNumber = 47,
                            LastName = "Baertschi",
                            Position = "Forward",
                            TeamName = "Canucks"
                        },
                        new
                        {
                            PlayerId = 2,
                            FirstName = "Hendrik",
                            JerseyNumber = 33,
                            LastName = "Sedin",
                            Position = "Left Wing",
                            TeamName = "Canucks"
                        },
                        new
                        {
                            PlayerId = 3,
                            FirstName = "John",
                            JerseyNumber = 12,
                            LastName = "Rooster",
                            Position = "Right Wing",
                            TeamName = "Flames"
                        },
                        new
                        {
                            PlayerId = 4,
                            FirstName = "Bob",
                            JerseyNumber = 44,
                            LastName = "Plumber",
                            Position = "Defense",
                            TeamName = "Oilers"
                        },
                        new
                        {
                            PlayerId = 5,
                            FirstName = "Connor",
                            JerseyNumber = 97,
                            LastName = "McDavid",
                            Position = "Center",
                            TeamName = "Oilers"
                        },
                        new
                        {
                            PlayerId = 6,
                            FirstName = "Nathan",
                            JerseyNumber = 29,
                            LastName = "MacKinnon",
                            Position = "Center",
                            TeamName = "Sharks"
                        },
                        new
                        {
                            PlayerId = 7,
                            FirstName = "Alex",
                            JerseyNumber = 8,
                            LastName = "Ovechkin",
                            Position = "Left Wing",
                            TeamName = "Lightening"
                        },
                        new
                        {
                            PlayerId = 8,
                            FirstName = "Sidney",
                            JerseyNumber = 87,
                            LastName = "Crosby",
                            Position = "Center",
                            TeamName = "Ducks"
                        },
                        new
                        {
                            PlayerId = 9,
                            FirstName = "Patrick",
                            JerseyNumber = 88,
                            LastName = "Kane",
                            Position = "Right Wing",
                            TeamName = "Blackhawks"
                        },
                        new
                        {
                            PlayerId = 10,
                            FirstName = "Auston",
                            JerseyNumber = 34,
                            LastName = "Matthews",
                            Position = "Center",
                            TeamName = "Leafs"
                        },
                        new
                        {
                            PlayerId = 11,
                            FirstName = "Steven",
                            JerseyNumber = 91,
                            LastName = "Stamkos",
                            Position = "Center",
                            TeamName = "Leafs"
                        },
                        new
                        {
                            PlayerId = 12,
                            FirstName = "Carey",
                            JerseyNumber = 11,
                            LastName = "Price",
                            Position = "Goaltender",
                            TeamName = "Flames"
                        },
                        new
                        {
                            PlayerId = 13,
                            FirstName = "Victor",
                            JerseyNumber = 77,
                            LastName = "Hedman",
                            Position = "Defense",
                            TeamName = "Oilers"
                        },
                        new
                        {
                            PlayerId = 14,
                            FirstName = "Johnny",
                            JerseyNumber = 13,
                            LastName = "Gaudreau",
                            Position = "Left Wing",
                            TeamName = "Canucks"
                        },
                        new
                        {
                            PlayerId = 15,
                            FirstName = "Kris",
                            JerseyNumber = 58,
                            LastName = "Letang",
                            Position = "Defense",
                            TeamName = "Sharks"
                        },
                        new
                        {
                            PlayerId = 16,
                            FirstName = "Tuukka",
                            JerseyNumber = 40,
                            LastName = "Rask",
                            Position = "Goaltender",
                            TeamName = "Ducks"
                        },
                        new
                        {
                            PlayerId = 17,
                            FirstName = "Mitch",
                            JerseyNumber = 16,
                            LastName = "Marner",
                            Position = "Right Wing",
                            TeamName = "Blackhawks"
                        },
                        new
                        {
                            PlayerId = 18,
                            FirstName = "Anze",
                            JerseyNumber = 11,
                            LastName = "Kopitar",
                            Position = "Center",
                            TeamName = "Lightening"
                        },
                        new
                        {
                            PlayerId = 19,
                            FirstName = "Sergei",
                            JerseyNumber = 72,
                            LastName = "Bobrovsky",
                            Position = "Goaltender",
                            TeamName = "Oilers"
                        },
                        new
                        {
                            PlayerId = 20,
                            FirstName = "Ryan",
                            JerseyNumber = 17,
                            LastName = "O'Reilly",
                            Position = "Center",
                            TeamName = "Canucks"
                        },
                        new
                        {
                            PlayerId = 21,
                            FirstName = "Marc-Andre",
                            JerseyNumber = 29,
                            LastName = "Fleury",
                            Position = "Goaltender",
                            TeamName = "Sharks"
                        },
                        new
                        {
                            PlayerId = 22,
                            FirstName = "Mika",
                            JerseyNumber = 93,
                            LastName = "Zibanejad",
                            Position = "Center",
                            TeamName = "Lightening"
                        },
                        new
                        {
                            PlayerId = 23,
                            FirstName = "John",
                            JerseyNumber = 74,
                            LastName = "Carlson",
                            Position = "Defense",
                            TeamName = "Ducks"
                        },
                        new
                        {
                            PlayerId = 24,
                            FirstName = "David",
                            JerseyNumber = 88,
                            LastName = "Pastrnak",
                            Position = "Right Wing",
                            TeamName = "Blackhawks"
                        },
                        new
                        {
                            PlayerId = 25,
                            FirstName = "Roman",
                            JerseyNumber = 59,
                            LastName = "Josi",
                            Position = "Defense",
                            TeamName = "Leafs"
                        },
                        new
                        {
                            PlayerId = 26,
                            FirstName = "Jonathan",
                            JerseyNumber = 19,
                            LastName = "Toews",
                            Position = "Center",
                            TeamName = "Flames"
                        },
                        new
                        {
                            PlayerId = 27,
                            FirstName = "Patrice",
                            JerseyNumber = 37,
                            LastName = "Bergeron",
                            Position = "Center",
                            TeamName = "Oilers"
                        },
                        new
                        {
                            PlayerId = 28,
                            FirstName = "Artemi",
                            JerseyNumber = 10,
                            LastName = "Panarin",
                            Position = "Left Wing",
                            TeamName = "Canucks"
                        },
                        new
                        {
                            PlayerId = 29,
                            FirstName = "Evgeni",
                            JerseyNumber = 71,
                            LastName = "Malkin",
                            Position = "Center",
                            TeamName = "Sharks"
                        },
                        new
                        {
                            PlayerId = 30,
                            FirstName = "Sidney",
                            JerseyNumber = 21,
                            LastName = "Hoyt",
                            Position = "Defense",
                            TeamName = "Blackhawks"
                        });
                });

            modelBuilder.Entity("MvcDB.Web.Models.Team", b =>
                {
                    b.Property<string>("TeamName")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TeamName");

                    b.ToTable("Team", (string)null);

                    b.HasData(
                        new
                        {
                            TeamName = "Canucks",
                            City = "Vancouver",
                            Country = "Canada",
                            Province = "BC"
                        },
                        new
                        {
                            TeamName = "Sharks",
                            City = "San Jose",
                            Country = "USA",
                            Province = "CA"
                        },
                        new
                        {
                            TeamName = "Oilers",
                            City = "Edmonton",
                            Country = "Canada",
                            Province = "AB"
                        },
                        new
                        {
                            TeamName = "Flames",
                            City = "Calgary",
                            Country = "Canada",
                            Province = "AB"
                        },
                        new
                        {
                            TeamName = "Leafs",
                            City = "Toronto",
                            Country = "Canada",
                            Province = "ON"
                        },
                        new
                        {
                            TeamName = "Ducks",
                            City = "Anaheim",
                            Country = "USA",
                            Province = "CA"
                        },
                        new
                        {
                            TeamName = "Lightening",
                            City = "Tampa Bay",
                            Country = "USA",
                            Province = "FL"
                        },
                        new
                        {
                            TeamName = "Blackhawks",
                            City = "Chicago",
                            Country = "USA",
                            Province = "IL"
                        });
                });

            modelBuilder.Entity("MvcDB.Web.Models.Player", b =>
                {
                    b.HasOne("MvcDB.Web.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("MvcDB.Web.Models.Team", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
